version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install'
    
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Pre build'
    
  build:
    on-failure: ABORT
    commands:
      - echo 'Build'
    
  post_build:
    on-failure: ABORT
    commands:
      - echo 'Post build'